apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-goapp-ingress
  namespace: dev
  labels:
    app: whoami-goapp
    environment: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: whoami.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-goapp
            port:
              number: 80
